# Site settings
title: "Alex On Tech"
email: alex@alexontech.net
description: "Just another tech blog"
baseurl: ""
url: "http://alexontech.net/"
title_description: "I'm a software engineer from Ohio. Stick around and you'll find fun articles on javascript, css, and general tech ideas."
title_image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png"
google_analytics: "UA-159113257-1"
disqus_account: acarroll94
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-5e55b3dbcd73e43e
post_limit: 5

# Social usernames/URLs
# twitter_username:
# github_username:  alex-tgk
# instagram_username: alexcarroll94
# reddit_username:
# linkedin_link: https://www.linkedin.com/in/alexandertcarroll/
# facebook_link: https://www.facebook.com/AlexandertCarroll

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
